config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recommendations, only: [:index]
  resources :articles, only: %i[index show]

  get "statistics", to: "pages#statistics", as: :statistics
  # Defines the root path route ("/")
  # root "posts#index"

  get 'profile', to: 'pages#profile', as: 'profile'

  get 'landing', to: 'pages#landing', as: 'landing'

  resources :user_appliances, only: %i[index show edit new create destroy] do
    resources :routines, only: %i[index new create] # do
    #   resources :recommendations, only: [:index, :show]
    # end
  end

  resources :routines, only: %i[create show update edit destroy] do
    resources :recommendations, only: [:index]
  end
  resources :prices, only: %i[index create]

  # New route for all recommendations
  get 'recommendations/all', to: 'recommendations#all', as: :all_recommendations
end

app/models/article.rb
class Article < ApplicationRecord
  # Validations
  validates :title, presence: true
  validates :content, presence: true
  
 # validates :category, presence: true, inclusion: { in: [
 #   'air conditioning', 'washing machine', 'dishwasher', 'EV Charger', 'heating', 'TV & Consoles'
 # ] }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @generic_articles = Article.where(user_appliance_id: nil)
    @my_articles = Article.all.reject { |article| article.user_appliance_id == nil }
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/views/articles/index.html.erb
<%# Overview of all articles %>
<div class="d-flex mt-3 mb-2">
  <input type="button" value="All" class= "border-0 shadow-none" style="background-color:#EBFF57; width:50%; ; border-radius: 4px; margin-right: 3px;">
  <input type="button" value="Favorites" class="btn border-0 shadow-none italic-button" style="width:50%; border-radius: 4px;margin-left: 3px;">
</div>
<div class="tree-icon ml-3 d-flex">
  <%= image_tag "tree.svg", alt: "Tree" %>
  <div class="mt-1 ms-2 flex-grow-1" style="font-size: 20px;"><p> Sustainable life<p></div>
    <%= image_tag "showmore.svg", alt: "Tree" %>
</div>
<div class="article-subtitle mb-2">
  <p style="margin-left: 9px;"> Read more about sustainability</p>
</div>

<div class="panel-container" id="article-left" >
  <% @generic_articles.each do |article| %>
    <div class="panel article-panel" style="background-image:
              linear-gradient(to bottom, rgba(0, 0, 0, 0.9) 0%, rgba(0, 0, 0, 0) 50%),
              linear-gradient(to top, rgba(0, 0, 0, 1.2) 0%, rgba(0, 0, 0, 0) 50%),
              url('<%= asset_path("#{article.subcategory}.jpg") %>');>">
      <div class="star-icon-top">
        <%= image_tag "star.svg", alt: "Star" %>
      </div>
      <div class="article-title">
        <p><%= link_to article.title, article_path(article) %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="tree-icon ml-3 d-flex">
  <%= image_tag "tree.svg", alt: "Tree" %>
  <div class="mt-1 ms-2 flex-grow-1" style="font-size: 20px;"><p>Tips & Tricks</p></div>
  <%= image_tag "showmore.svg", alt: "Tree" %>
</div>
<div class="article-subtitle mb-2">
  <p style="margin-left: 9px;"> Articles, special for <%= current_user.username %></p>
</div>

<div class="panel-container" id="article-left">
<% @my_articles.each do |article| %>
  <div class="panel article-panel" style="background-image:
            linear-gradient(to bottom, rgba(0, 0, 0, 0.9) 0%, rgba(0, 0, 0, 0) 50%),
            linear-gradient(to top, rgba(0, 0, 0, 1.2) 0%, rgba(0, 0, 0, 0) 50%),
            url('<%= asset_path("#{article.subcategory}.jpg") %>');>">
    <div class="star-icon-top">
        <%= image_tag "star.svg", alt: "Star" %>
      </div>
    <div class="article-title">
      <p><%= link_to article.title.truncate(40), article_path(article) %></p>
    </div>
  </div>
<% end %>
</div>

app/views/articles/show.html.erb
<div class="article-container">
  <div class="banner">
    <%= image_tag "#{@article.subcategory}.jpeg", alt: @article.title %>
    <div class="banner-overlay">
      <h1><%= @article.title %></h1>
    </div>
    <div class="exit-icon">
      <%= link_to articles_path do %>
        <%= image_tag "exit.svg", alt: "Close" %>
        <% end %>
    </div>
    <div class="star-icon">
      <%= image_tag "star.svg", alt: "Star" %>
    </div>
  </div>

  <div class="article-content m-3" id="article-bottom">
    <p><%= @article.content.html_safe %></p>
  </div>
</div>