config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recommendations, only: [:index]
  resources :articles, only: %i[index show]

  get "statistics", to: "pages#statistics", as: :statistics
  # Defines the root path route ("/")
  # root "posts#index"

  get 'profile', to: 'pages#profile', as: 'profile'

  get 'landing', to: 'pages#landing', as: 'landing'

  resources :user_appliances, only: %i[index show edit new create destroy] do
    resources :routines, only: %i[index new create] # do
    #   resources :recommendations, only: [:index, :show]
    # end
  end

  resources :routines, only: %i[create show update edit destroy] do
    resources :recommendations, only: [:index]
  end
  resources :prices, only: %i[index create]

  # New route for all recommendations
  get 'recommendations/all', to: 'recommendations#all', as: :all_recommendations
end

app/views/shared/_flashes.html.erb
<% unless current_page?(new_user_session_path) %>
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-controller="alert">
      <%= notice %>
      <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button> %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-controller="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-container">
    <ul class="navbar-links">
      <% if user_signed_in? %>
        <li>
          <%= link_to root_path, class: "nav-link #{'active' if current_page?(root_path)}" do %>
            <%= image_tag "icon-home#{'-active' if current_page?(root_path)}.svg" %>
          <% end %>
        </li>
        <li>
          <%= link_to recommendations_path, class: "nav-link #{'active' if current_page?(recommendations_path)}" do %>
            <%= image_tag "icon-recommendation#{'-active' if current_page?(all_recommendations_path)}.svg" %>
          <% end %>
        </li>
        <li>
          <%= link_to user_appliances_path, class: "nav-link #{'active' if current_page?(user_appliances_path)}" do %>
            <%= image_tag "icon-appliance#{'-active' if current_page?(user_appliances_path)}.svg" %>
          <% end %>
        </li>
        <li>
          <%= link_to statistics_path, class: "nav-link #{'active' if current_page?(statistics_path)}" do %>
            <%= image_tag "icon-statistic#{'-active' if current_page?(statistics_path)}.svg" %>
          <% end %>
        </li>
        <li>
          <%= link_to articles_path, class: "nav-link #{'active' if current_page?(articles_path)}" do %>
            <%= image_tag "icon-article#{'-active' if current_page?(articles_path)}.svg" %>
          <% end %>
        </li>
        <%# <li> %>
          <%#= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" do %>
            <%# <i class="fas fa-sign-out-alt"></i> %>
          <%# end %>
        <%# </li> %>
      <%# else %>
        <%# <li> %>
          <%#= link_to new_user_session_path, class: "nav-link #{'active' if current_page?(new_user_session_path)}" do %>
            <%# <i class="fas fa-sign-in-alt"></i> %>
          <%# end %>
        <%# </li> %>
      <% end %>
    </ul>
  </div>
</nav>