config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recommendations, only: [:index]
  resources :articles, only: %i[index show]

  get "statistics", to: "pages#statistics", as: :statistics
  # Defines the root path route ("/")
  # root "posts#index"

  get 'profile', to: 'pages#profile', as: 'profile'

  get 'landing', to: 'pages#landing', as: 'landing'

  resources :user_appliances, only: %i[index show edit new create destroy] do
    resources :routines, only: %i[index new create] # do
    #   resources :recommendations, only: [:index, :show]
    # end
  end

  resources :routines, only: %i[create show update edit destroy] do
    resources :recommendations, only: [:index]
  end
  resources :prices, only: %i[index create]

  # New route for all recommendations
  get 'recommendations/all', to: 'recommendations#all', as: :all_recommendations
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

  </head>

  <body class="<%= "#{controller.controller_name}-#{controller.action_name}" %>">
    <% unless current_page?(landing_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) %><%= render "shared/navbar" %><% end %>

      <%= render "shared/flashes" %>

      <% unless current_page?(landing_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
      <div class="my-own-space">
        <%= link_to profile_path, class: "yellow-circle on-top" do %>
          <%= image_tag 'spark.svg' %>
        <% end %>
      </div>
      <% end %>

      <div class="on-top"><%= yield %></div>

      <% unless current_page?(new_user_session_path) %>
        <div class="overlay"></div>
        <%= image_tag 'blob.svg', class: "blob" %>
      <% end %>
    </div>
  </body>
</html>